[project]
name = "pipelines"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "(bot) Dipsy Wong", email = "ycwongal@connect.ust.hk" }
]
requires-python = ">=3.10"
dependencies = [
    "onnx>=1.17.0",
    "onnx-simplifier>=0.4.36",
    "onnxscript>=0.2.5",
    "pandas>=2.2.3",
    "pyarrow>=20.0.0",
    "sagemaker>=2.244.0",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
    "typer>=0.15.4",
]

# [project.scripts]
# pipelines = "pipelines:main"

[tool.uv.sources]
# pipelines = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
