[project]
name = "functions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "(bot) Dipsy Wong", email = "ycwongal@connect.ust.hk" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
functions = "functions:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
