on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["packages/pipelines/**"]

  pull_request:
    branches: [main]
    paths: ["packages/pipelines/**"]


jobs:
  upsert-mnist-pipeline:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync
      - run: uv run packages/pipelines/src/pipelines/mnist/pipeline.py --run-pipeline=True
