on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["packages/pipelines/**"]

  pull_request:
    branches: [main]
    paths: ["packages/pipelines/**"]


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure --verbose
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync
      - name: Run Tests
        run: uv run pytest tests

  upsert-mnist-pipeline:
    runs-on: ubuntu-22.04
    if: github.event_name == 'workflow_dispatch' && success()
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync

      # TODO: see if can use local sagemaker
      - run: uv run packages/pipelines/src/pipelines/mnist/pipeline.py --run-pipeline=False --epoch=1
