on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  #   # paths: ["terraform/**"]
  #   paths: ["**"]

  # pull_request:
  #   branches: [main]
  #   # paths: ["terraform/**"]
  #   paths: ["**"]


jobs:
  plan:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Initialise project and view terraform plan
        run: |
          cd terraform
          terraform fmt
          terraform init
          terraform plan

  deploy:
    name: Terraform Deploy
    needs: plan
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Initialise project and deploy terraform
        run: |
          cd terraform
          terraform fmt
          terraform init
          terraform apply --auto-approve=true
